# Generated by Django 5.2.7 on 2025-11-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_results_score_alter_registration_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
