# Generated by Django 5.2.7 on 2025-11-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_leaderboardresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderboardResult',
        ),
    ]
