# Generated by Django 5.2.7 on 2025-11-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_delete_leaderboardresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_results', to='sports.sport')),
            ],
            options={
                'ordering': ['-points', 'branch'],
                'unique_together': {('sport', 'branch')},
            },
        ),
    ]
