# Generated by Django 5.2.7 on 2025-11-26 20:07

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_leaderboardresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaderboardresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leaderboardresult',
            name='sport',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='results',
            name='user',
        ),
        migrations.AddField(
            model_name='results',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(choices=[('COMPS', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'CSE Artificial Intelligence and Machine Learning'), ('DS', 'CSE Data Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], default='COMPS', max_length=6),
        ),
        migrations.AlterField(
            model_name='results',
            name='points',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated: 3 for 1st, 2 for 2nd, 1 for 3rd'),
        ),
        migrations.AlterField(
            model_name='results',
            name='position',
            field=models.PositiveIntegerField(help_text='1 for 1st, 2 for 2nd, 3 for 3rd'),
        ),
        migrations.AlterField(
            model_name='results',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='Points earned in the match/game itself'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='secondary',
            field=models.ManyToManyField(blank=True, related_name='secondary_sports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='branch',
            field=models.CharField(choices=[('COMPS', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'CSE Artificial Intelligence and Machine Learning'), ('DS', 'CSE Data Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], default='COMPS', max_length=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'sport')},
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['student', 'sport'], name='sports_regi_student_b5bc5a_idx'),
        ),
        migrations.AddIndex(
            model_name='results',
            index=models.Index(fields=['sport', 'position'], name='sports_resu_sport_i_d80aab_idx'),
        ),
        migrations.AddIndex(
            model_name='results',
            index=models.Index(fields=['sport', 'branch'], name='sports_resu_sport_i_e5a5af_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['sport', 'branch'], name='sports_team_sport_i_25eae0_idx'),
        ),
        migrations.AddConstraint(
            model_name='results',
            constraint=models.CheckConstraint(condition=models.Q(('team__isnull', False), ('player__isnull', False), _connector='OR'), name='team_or_player_required'),
        ),
        migrations.AddConstraint(
            model_name='results',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('sport', 'team'), name='unique_team_per_sport'),
        ),
        migrations.AddConstraint(
            model_name='results',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('sport', 'player'), name='unique_player_per_sport'),
        ),
        migrations.DeleteModel(
            name='LeaderboardResult',
        ),
    ]
