# Generated by Django 5.2.7 on 2025-11-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_teamrequest_and_more'),
        ('sports', '0013_alter_results_player_alter_results_team'),
    ]

    operations = [
    ]
