# Generated by Django 5.2.7 on 2025-11-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0014_merge_20251130_0316'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_student_sport_registration',
        ),
    ]
