# Generated by Django 5.2.7 on 2025-12-22 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0015_remove_registration_unique_student_sport_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sport',
            name='img',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='teamSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sport',
            name='time',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.RemoveField(
            model_name='sport',
            name='primary',
        ),
        migrations.AddField(
            model_name='sport',
            name='primary',
            field=models.ManyToManyField(related_name='primary_sports', to=settings.AUTH_USER_MODEL),
        ),
    ]
