# Generated by Django 5.2.7 on 2025-12-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0016_sport_day_sport_img_sport_teamsize_sport_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamSize',
            field=models.IntegerField(default=0),
        ),
    ]
