# Generated by Django 5.2.7 on 2025-12-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0016_sport_day_sport_img_sport_teamsize_sport_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('TE', 'Third Year (TE)'), ('BE', 'Fourth Year (BE)')], default='indoor', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='teamSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(choices=[('COMPS', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'CSE Artificial Intelligence and Machine Learning'), ('DS', 'CSE Data Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='branch',
            field=models.CharField(choices=[('COMPS', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'CSE Artificial Intelligence and Machine Learning'), ('DS', 'CSE Data Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=6),
        ),
    ]
