# Generated by Django 5.2.7 on 2025-12-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_team_teamsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(choices=[('COMPS', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'CSE Artificial Intelligence and Machine Learning'), ('DS', 'CSE Data Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='branch',
            field=models.CharField(choices=[('COMPS', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'CSE Artificial Intelligence and Machine Learning'), ('DS', 'CSE Data Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=6),
        ),
    ]
