# Generated by Django 5.2.7 on 2025-12-27 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_sport_category_team_teamsize_and_more'),
        ('sports', '0018_alter_registration_branch_alter_team_branch'),
    ]

    operations = [
    ]
