# Generated by Django 5.2.7 on 2026-02-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_team_teamsize_alter_registration_branch_and_more'),
        ('sports', '0019_merge_20251228_0255'),
    ]

    operations = [
    ]
