# Generated by Django 5.2.7 on 2026-02-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0020_merge_20260204_0832'),
        ('sports', '0020_merge_20260204_1010'),
    ]

    operations = [
    ]
