# Generated by Django 5.2.7 on 2025-12-27 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('registeration', models.BooleanField(default=False)),
                ('venue', models.CharField(default='', max_length=50)),
                ('day', models.IntegerField(default=1)),
                ('time', models.CharField(default='', max_length=5)),
                ('img', models.URLField(default='')),
                ('primary', models.ManyToManyField(blank=True, related_name='cultural_primary_events', to=settings.AUTH_USER_MODEL)),
                ('secondary', models.ManyToManyField(blank=True, related_name='cultural_secondary_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FE', 'First Year (FE)'), ('SE', 'Second Year (SE)'), ('TE', 'Third Year (TE)'), ('BE', 'Fourth Year (BE)')], default='FE', max_length=2)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultural.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'event'], name='cultural_re_student_c5ad8f_idx')],
                'unique_together': {('student', 'event')},
            },
        ),
    ]
