# Generated by Django 5.2.7 on 2026-02-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
