# Generated by Django 5.2.7 on 2026-02-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultural', '0003_team_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='team',
            new_name='cultural_te_event_i_1e3a43_idx',
            old_name='cultural_team_e_l_123456_idx',
        ),
    ]
