# Generated by Django 5.2.7 on 2026-02-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultural', '0004_rename_cultural_team_e_l_123456_idx_cultural_te_event_i_1e3a43_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
