# Generated by Django 5.2.7 on 2026-01-29 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FE', 'First Year (FE)'), ('SE', 'Second Year (SE)'), ('TE', 'Third Year (TE)'), ('BE', 'Fourth Year (BE)')], max_length=2)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student',), name='unique_booking_per_student')],
            },
        ),
    ]
