# Generated by Django 5.2.7 on 2026-01-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
